
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Alberto Villarreal
 */
public class Ventanilla extends javax.swing.JFrame {

    public Ventanilla() throws FileNotFoundException, IOException, ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        String laf = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(laf);
        setLocationRelativeTo(null);
        setTitle("Forex Predictor"); //Titulo del programa
        setResizable(false); //Remueve el boton de maximizar pantalla
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        setSize(465, 425);
        InflacionTestField.setEnabled(true);
        ConvenienciaTestField.setEnabled(true);
        InvertirField.setEditable(false);
        CallPutField.setEditable(false);
        String archivo = "paridad.txt";
        File file = new File(archivo);
        FileInputStream fis = new FileInputStream(file);
        InputStreamReader isr = new InputStreamReader(fis);
        BufferedReader br = new BufferedReader(isr);

        String line;
        
        while((line = br.readLine()) != null){
        //process the line
        ParidadComboBox.addItem(line);
        System.out.println(line);
        }
        br.close();
        InvertirField.setText("-");
        CallPutField.setText("-");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreditosLabel = new javax.swing.JLabel();
        TituloLabel = new javax.swing.JLabel();
        ParidadLabel = new javax.swing.JLabel();
        Precio4hLabel = new javax.swing.JLabel();
        ParidadComboBox = new javax.swing.JComboBox<>();
        Precio4hField = new javax.swing.JTextField();
        PrecioBELabel = new javax.swing.JLabel();
        PrecioBEField = new javax.swing.JTextField();
        InflacionTestField = new javax.swing.JTextField();
        InflacionTestLabel = new javax.swing.JLabel();
        ConvenienciaTestLabel = new javax.swing.JLabel();
        ConvenienciaTestField = new javax.swing.JTextField();
        EvaluarButton = new javax.swing.JButton();
        ResultadoLabel = new javax.swing.JLabel();
        InvertirField = new javax.swing.JTextField();
        InvertirLabel = new javax.swing.JLabel();
        CallPutLabel = new javax.swing.JLabel();
        CallPutField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 395));

        jPanel1.setLayout(null);

        CreditosLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        CreditosLabel.setText("© 2018 Betusto/Aldo Napoles");
        jPanel1.add(CreditosLabel);
        CreditosLabel.setBounds(140, 370, 200, 30);

        TituloLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        TituloLabel.setText("Forex Predictor");
        jPanel1.add(TituloLabel);
        TituloLabel.setBounds(142, 10, 190, 50);

        ParidadLabel.setText("Paridad");
        jPanel1.add(ParidadLabel);
        ParidadLabel.setBounds(20, 80, 60, 20);

        Precio4hLabel.setText("Precio. hace 4 hrs.");
        jPanel1.add(Precio4hLabel);
        Precio4hLabel.setBounds(170, 80, 110, 20);

        ParidadComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParidadComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ParidadComboBox);
        ParidadComboBox.setBounds(20, 110, 120, 20);

        Precio4hField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio4hFieldActionPerformed(evt);
            }
        });
        jPanel1.add(Precio4hField);
        Precio4hField.setBounds(170, 110, 120, 20);

        PrecioBELabel.setText("Precio. BE.");
        jPanel1.add(PrecioBELabel);
        PrecioBELabel.setBounds(320, 80, 100, 20);

        PrecioBEField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                PrecioBEFieldInputMethodTextChanged(evt);
            }
        });
        PrecioBEField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioBEFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PrecioBEField);
        PrecioBEField.setBounds(320, 110, 120, 20);

        InflacionTestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InflacionTestFieldActionPerformed(evt);
            }
        });
        jPanel1.add(InflacionTestField);
        InflacionTestField.setBounds(70, 170, 120, 20);

        InflacionTestLabel.setText("Inflación:");
        jPanel1.add(InflacionTestLabel);
        InflacionTestLabel.setBounds(10, 170, 90, 20);

        ConvenienciaTestLabel.setText("Conveniencia: ");
        jPanel1.add(ConvenienciaTestLabel);
        ConvenienciaTestLabel.setBounds(210, 170, 130, 20);

        ConvenienciaTestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvenienciaTestFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ConvenienciaTestField);
        ConvenienciaTestField.setBounds(300, 170, 120, 20);

        EvaluarButton.setText("Evaluar");
        EvaluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EvaluarButton);
        EvaluarButton.setBounds(170, 230, 120, 23);

        ResultadoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultadoLabel.setText("Resultado:");
        jPanel1.add(ResultadoLabel);
        ResultadoLabel.setBounds(20, 270, 70, 20);
        jPanel1.add(InvertirField);
        InvertirField.setBounds(100, 330, 120, 20);

        InvertirLabel.setText("Invertir");
        jPanel1.add(InvertirLabel);
        InvertirLabel.setBounds(100, 300, 40, 20);

        CallPutLabel.setText("Call/Put");
        jPanel1.add(CallPutLabel);
        CallPutLabel.setBounds(250, 300, 60, 20);
        jPanel1.add(CallPutField);
        CallPutField.setBounds(250, 330, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ParidadComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParidadComboBoxActionPerformed

    }//GEN-LAST:event_ParidadComboBoxActionPerformed

    private void Precio4hFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio4hFieldActionPerformed

    }//GEN-LAST:event_Precio4hFieldActionPerformed

    private void PrecioBEFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_PrecioBEFieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioBEFieldInputMethodTextChanged

    private void PrecioBEFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioBEFieldActionPerformed

    }//GEN-LAST:event_PrecioBEFieldActionPerformed

    private void InflacionTestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InflacionTestFieldActionPerformed

    }//GEN-LAST:event_InflacionTestFieldActionPerformed

    private void ConvenienciaTestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvenienciaTestFieldActionPerformed

    }//GEN-LAST:event_ConvenienciaTestFieldActionPerformed

    private void EvaluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluarButtonActionPerformed
        String precio4 = Precio4hField.getText();
        String Inflacion = InflacionTestField.getText();
        String Conveniencia = ConvenienciaTestField.getText();
        String Preciobe = PrecioBEField.getText();
        if (!"".equals(precio4) && !"".equals(Inflacion) && !"".equals(Preciobe) && !"".equals(Conveniencia)){
        double number1 = Double.parseDouble(precio4);
        double number2 = Double.parseDouble(Preciobe);
        double numero = ((number2 - number1) / 4.0);
        String Tendencia = String.valueOf(numero);
        double ConvenienciaDouble = Double.parseDouble(Conveniencia);
        double TendenciaDouble = Double.parseDouble(Tendencia);
        double InflacionDouble = Double.parseDouble(Inflacion);       
        SistemaDifuso Evaluar = new SistemaDifuso(ConvenienciaDouble, TendenciaDouble, InflacionDouble);
        double number3 = Evaluar.getOportunidad();
        if (number3 <= 35.0) {
            InvertirField.setText("Sí.");
            CallPutField.setText("Put/Sell.");
        } else {
            if ((35.0 < number3) && (number3 <= 70.0)) {
                InvertirField.setText("No.");
                CallPutField.setText("-");
            } else {
                if (70.0 < number3) {
                    InvertirField.setText("Sí.");
                    CallPutField.setText("Call/Buy.");
                }
            
        }
    }//GEN-LAST:event_EvaluarButtonActionPerformed
    }
        else{
        InvertirField.setText("-");
        CallPutField.setText("-");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ventanilla().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Ventanilla.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Ventanilla.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Ventanilla.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Ventanilla.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Ventanilla.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CallPutField;
    private javax.swing.JLabel CallPutLabel;
    private javax.swing.JTextField ConvenienciaTestField;
    private javax.swing.JLabel ConvenienciaTestLabel;
    private javax.swing.JLabel CreditosLabel;
    private javax.swing.JButton EvaluarButton;
    private javax.swing.JTextField InflacionTestField;
    private javax.swing.JLabel InflacionTestLabel;
    private javax.swing.JTextField InvertirField;
    private javax.swing.JLabel InvertirLabel;
    private javax.swing.JComboBox<String> ParidadComboBox;
    private javax.swing.JLabel ParidadLabel;
    private javax.swing.JTextField Precio4hField;
    private javax.swing.JLabel Precio4hLabel;
    private javax.swing.JTextField PrecioBEField;
    private javax.swing.JLabel PrecioBELabel;
    private javax.swing.JLabel ResultadoLabel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
